version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "bootstrap/**",
  "resources/**",
  "storage/**",
  "database/**"
]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true